apiVersion: v1
kind: Service # declare Service object
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-app # This Service object will find lable `nginx-app`
  ports:
    - targetPort: 80 # specifies which port the Service will be accessible on, that is, internally in the cluster
      port: 80 # specifies the port in the Pod where the requests will be forward to
      nodePort: 30080 # specifies which port the Service will be externally accessible on using any of the nodes in the cluster. by default, port range from 30000 to 32767